### ISSUE TITLE
Readme Example Typo

### ISSUE THREAD

**Issue by austinhulak** [jrpotter/django-pipeline-node-sass#2]
This is a minor issue, but the Readme example references:

```
PIPELINE_COMPILERS = (
    'pipeline_node_sass.compiler**s**.NodeSassCompiler',
)
```

when in fact it should be:

```
PIPELINE_COMPILERS = (
    'pipeline_node_sass.compiler.NodeSassCompiler',
)
```

Not a big deal, but easy to miss if your just trying to quickly setup node-sass

**Comment by jrpotter** [comment]
Thanks for the heads up. Just merged.
